Add a Tabular data block that can handle simple CSVs and text files
the-grey-group/datalab pull request #592
Opened 2024-02-16 10:55 UTC by ml-evs

This PR adds a simple block that passes a data file through `pd.read_csv()` and allows you to make a selectable  scatter plot of its columns. It also adds a base component `BokehBlock` that can probably be used by several other blocks with minor tweaking of the supported extensions (which should be dynamic soon anyway).

We could make this increasingly useful by being more robust with `read_csv` args and maybe wrapping our own file reader. e.g., I took some random SECM data and realised that the header is formatted in such a way that pandas fails to read it. I think one nice idea could be to write a wrapper to `read_csv` that does a binary search to detect the header 'properly', or b) reads a CSV file in reverse, populates the values until the first "broken" line, then treats them as column headers (this could actually be very useful generally, e.g., within pandas itself).

2024-02-16 20:32 UTC, jdbocarsly commented
Awesome!! This is going to be super useful. 

Already works for me for a basic csv file, but some thoughts on possible future developments:

I agree that a UI to set the parameters for read_csv would be great. I've been thinking of something with live feedback (i.e. you can see the file, and see how changing the parameters splits it up differently, like some spreedsheet applications can do). That's probably a longer term goal, but for now, just having options for `sep`, `skip_rows`, and `comment` would probably work for a majority of cases. (your idea of reading csvs backwards is interesting too...)

Adding a UI for naming/renaming columns and potentially dropping spurious columns would be the other useful feature, but would take more work. Add a button to open in google drive??

Incidentally, by adding `sep=None` to the `read_csv` call, pandas automatically tries to guess the separator using `csv.Sniffer().sniff()`. I tested this out, and it worked pretty well and let me read a variety of files including some .csv cycling data and some .xye synchrotron data (tab-delimited). If we want to add the UI for specifying skip_rows, etc., we can explicitely use Sniffer to guess starting parameters.

2024-02-16 20:34 UTC, jdbocarsly commented
A few more immediate comments:

- When I tried an invalid file, it through an error and make it so that I couldn't reload the sample ever again without erroring.
- Unfortunately our `selectable_axis_plot` doesn't save the selected columns anywhere, so you have to reselect the correct columns every time you load the page. I wonder if we can figure out an elegant way to save those. Honestly, it would probably involve moving the `select` components out of bokeh and generating them directly in vue so that they behave like all the other inputs in a block.
- Can you rename this to something like "CSVBlock", instead of "PlotterBlock"? The other blocks are named by what kind of data they deal with, rather than how they display the data.

2024-02-16 20:41 UTC, jdbocarsly reviewed
some thoughts

2024-02-16 20:41 UTC, jdbocarsly commented on pydatalab/pydatalab/blocks/common.py
> +class PlotterBlock(DataBlock):
```suggestion
class CSVBlock(DataBlock):
```

2024-02-16 20:41 UTC, jdbocarsly commented on webapp/src/resources.js
> +  plotter: { description: "Simple plot", component: BokehBlock },
```suggestion
  plotter: { description: "CSV file", component: BokehBlock },
```

2024-02-16 20:41 UTC, jdbocarsly commented on webapp/src/components/datablocks/BokehBlock.vue
I guess the idea is that this is a generic plotting component, which could be re-used for any other blocks that just need a plot?

2024-02-16 20:41 UTC, jdbocarsly commented on pydatalab/pydatalab/blocks/common.py
> +            return pd.read_csv(file_info["location"], skip_blank_lines=False)
```suggestion
            return pd.read_csv(file_info["location"], sep=None, skip_blank_lines=False)
```

2024-02-16 20:52 UTC, ml-evs commented on webapp/src/components/datablocks/BokehBlock.vue
Yeah potentially, I tried to rebase the Raman block on it but got stuck trying to do inheritance with the components listed in `resources.js`, e.g., something like

`'raman': {'component': defineComponent(extends: bokehBlock, ...)}` (modulo correct syntax) but it didn't seem particularly ergonomic

2024-02-16 21:11 UTC, ml-evs commented
Should be merged after #590

2024-05-18 14:57 UTC, ml-evs commented on pydatalab/pydatalab/blocks/common.py
> +    description = "Tabular Data Block"
```suggestion
    name = "Tabular Data Block"
    description = "This block will load tabular data from common plain text files and allow you to create simple scatter plots of the columns within."
```

2024-05-18 14:58 UTC, ml-evs commented
I think this is good enough for a first hash, would be good to get in before 0.4.0

2024-05-19 20:55 UTC, jdbocarsly requested changes
Works well, but I get a few unecessary warning displays when using:

1. When making a new block, I get the following warning before starting:
<img width="1250" alt="Screenshot 2024-05-19 at 3 48 05 PM" src="https://github.com/the-grey-group/datalab/assets/32345545/9cba0de7-58d8-47cd-a1e0-70f3735f8869">
2. When loading a sample.
<img width="1273" alt="Screenshot 2024-05-19 at 3 47 58 PM" src="https://github.com/the-grey-group/datalab/assets/32345545/3b1468e6-5c23-4dc4-97d3-3fc195c03544">

2024-05-19 20:55 UTC, jdbocarsly commented on pydatalab/pydatalab/blocks/common.py
> +            return pd.read_csv(file_info["location"], sep=None, skip_blank_lines=False)
```suggestion
            return pd.read_csv(file_info["location"], sep=None, skip_blank_lines=False, engine="python")
```

2024-05-27 14:50 UTC, ml-evs commented
> Works well, but I get a few unecessary warning displays when using:
> 
>     1. When making a new block, I get the following warning before starting:
> 
> 
> <img alt="Screenshot 2024-05-19 at 3 48 05 PM" width="1250" src="https://private-user-images.githubusercontent.com/32345545/331900537-9cba0de7-58d8-47cd-a1e0-70f3735f8869.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjE2NzYsIm5iZiI6MTcxNjgyMTM3NiwicGF0aCI6Ii8zMjM0NTU0NS8zMzE5MDA1MzctOWNiYTBkZTctNThkOC00N2NkLWExZTAtNzBmMzczNWY4ODY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE0NDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMDZiOWRmMmEwZjg4ZmYwYmE2ZjNjNGZhYWI0NDAwOWM3MTZmNTIzZjNkOTUzNWI1NjljNjg3MjAxZmUxZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNJVvJcD_JrTtMV4xdjqVsDkQ3A4MYdhvGI7RRgKeqY"> 2. When loading a sample. <img alt="Screenshot 2024-05-19 at 3 47 58 PM" width="1273" src="https://private-user-images.githubusercontent.com/32345545/331900461-3b1468e6-5c23-4dc4-97d3-3fc195c03544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjE2NzYsIm5iZiI6MTcxNjgyMTM3NiwicGF0aCI6Ii8zMjM0NTU0NS8zMzE5MDA0NjEtM2IxNDY4ZTYtNWMyMy00ZGM0LTk3ZDMtM2ZjMTk1YzAzNTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE0NDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YzkzODRiNTdmYjFhYmJjMmY0Y2ViYmNmZTM5YTQzNDRiY2ZlOTMzZGE5ZTE3MWUzZmMwODUzYTJlMzk4NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MrIc8LrFAcwZMF2XWzm_5Ry5_snf6TCq9BB-3kubQvY">

I've fixed these warnings, and also tweaked the pandas settings so that we can at least read the awkward Raman text files in our repo and a simple csv (with tests). Obviously there's no global solution for this unless we build out a whole UI, but think this should at least fail nicely...

2024-05-31 11:34 UTC, ml-evs commented
I'm going to merge this so we can get a feel for how useful it really is in production, having address @jdbocarsly's immediate comments

2024-05-31 17:01 UTC, merged